### ISSUE TITLE
Finish landing, signup, login, and matching design on Figma

### ISSUE THREAD

**Issue by Cdbryan** [Workspace-Recommendation-Engine/reco_eng#13]
View design here:

https://www.figma.com/file/oUZQkcvtV5knFREijaHhgb/Designs?node-id=0%3A1&t=iERbMgeGrI8ThNsf-1

**Comment by Cdbryan** [comment]
View design here: 

https://www.figma.com/file/oUZQkcvtV5knFREijaHhgb/Designs?node-id=0%3A1&t=iERbMgeGrI8ThNsf-1

**Comment by farahabuatiyeh** [comment]
maybe we can add a pop-up where it asks for user's location? 
so that the user doesn't have to always input the location and based on that, it is automated when the user clicks how far they wanna travel
