### ISSUE TITLE
google cloud access

### ISSUE THREAD

**Issue by farahabuatiyeh** [Workspace-Recommendation-Engine/reco_eng#14]
@Cdbryan please make sure we all have access to the Google Cloud

**Comment by Cdbryan** [comment]
Hey! Try out this link: https://console.firebase.google.com/u/2/project/reco-eng/overview

It should say Reco_eng and on the left-hand side there is an icon with 2 people, this is the authentication menu and you should be able to see test users there. When you add users to the react app they will pop up there.  Make sure the password for your users is at least 6 characters and that the test users have a real email ending such as @gmail.com
