### ISSUE TITLE
Build out Landing, signup, login, and matching front end on react app

### ISSUE THREAD

**Issue by Cdbryan** [Workspace-Recommendation-Engine/reco_eng#19]
- use the Figma and build out the react app for landing, signup, and login pages

**Comment by Cdbryan** [comment]
- Christian: Landing and Signup pages 
- Farah: Log in and Matching Page

**Comment by Cdbryan** [comment]
@farahabuatiyeh I made a branch called basic_frontend if you want to make a diff branch for your frontend pages that would be perfect, also if you want different frontend pages to do let me know I'm cool with anything!

**Comment by rivermd** [comment]
moved to Frontend + Backend
