### ISSUE TITLE
Frontend + Backend 

### ISSUE THREAD

**Issue by Cdbryan** [Workspace-Recommendation-Engine/reco_eng#25]

**Comment by rivermd** [comment]
Front end is nearly done, based on what we discussed during the last meeting. Here's a checklist of what is left:

- [ ] create API to try and connect frontend to backend
- [ ] create frontend for rating system for the cold start solution

**Comment by farahabuatiyeh** [comment]
Thank you for the update on the front-end development progress. It's great to hear that the front-end is nearly done based on our discussions during the last meeting. I appreciate you providing the checklist of what is left to be completed.

I'm glad to see that you have included creating an API to connect the front-end to the back-end in the checklist. This is an important step in ensuring that the system works seamlessly for the users.

I also see that creating a frontend for the rating system for the cold start solution is part of the checklist. This is an important feature to have in place, as it will allow new users to rate their preferences and receive accurate recommendations from the system.

Please keep me informed of any roadblocks that arise during the development process, and let's work together to ensure that we meet our deadlines and deliver a high-quality product.

**Comment by Cdbryan** [comment]
- [x] create API to try and connect frontend to backend
- [x] create frontend for rating system for the cold start solution
